### ISSUE TITLE
Error messages are not user friendly

### ISSUE THREAD

**Issue by Kashishjain04** [The-Robotics-Forum/sampark#11]
Everytime i try to signup I receive a message just saying response code: 400, and no further information about the error
![Screenshot 2021-01-05 at 11 58 29 PM](https://user-images.githubusercontent.com/55389276/103685094-a242ec80-4fb2-11eb-9e4a-f2f31236018e.png)

I can solve this issue,
please assign this to me

**Comment by nikhilbghodke** [comment]
yeah, these issue will be addressed when we integrate new signup and signin page

**Comment by nikhilbghodke** [comment]
basically this issue cannot be solved until new pages are made for the same
